### ISSUE TITLE
Tracking 2.0.0 Development

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#240]
This is a tracking issue for all of the known items that needs to be resolved for a 2.0 release.

- [x] Rename `development-1.6` branch to `development-2.0`
- [x] Instead of every subproject creating it's own off-line repo, create a subproject that will keep one on behalf of all subprojects.
- [x] Run all tests on Appveyor (gradle/gradle#5828)
- [x]  Write a multi-project compatibility test where an extension is created in one subproject and consumed by another asciidoctor subproject.
- [x] Set `includedir` attribute to be `sourceDir` or where intermediate is use, to the intermediate work directory.
- [x] Write integration tests for resources:
   - When 'resources' not specified, then copy all images to backend
   - When 'resources' not specified and more than one backend, then copy all images to every backend
   - When 'resources' are specified, then copy according to all patterns
- [x] Write integration tests for gemPath (#104)
- [x] Write a compatibility test which include `jruby-gradle` and requires some external GEMs.
- [x] Logging the classpath in JDK9/10. (The parent is no longer a URLClassLoader, but an internal platform classloader).
- [x] Utilise asciidoctor/asciidoctorj#643 and remove the current way of activating verbose mode.
   - LogHandler implementation for `IN_PROCESS` / `OUT_OF_PROCESS` modes. (#233)
   - Investigate whether parsing from the LogHandler can be used to fail builds under certain warning conditions. (#154)
- [x] Get rid of `The Cobertura XML file [null] is not accessible; skipping this rule` message.
- [x] ~Merge 1.5.8/1.5.8.1 changes to Asciidoctor compatiblity task~. Refactor internals of compatibility task to use `JAVA_EXEC` instead of the old in-memory oroxy cache model.
- [x] All default tasks must have a group and description.
- [x] Make tasks build-cache friendly by setting path sensitivity on inputs that are files.
- [x] The constructor of `AbstractAsciidoctorTask` still relies on an internal API. This needs to be resolved in another manner: `(resourceCopySpec as CopySpecInternal).buildRootResolver().allSource`  (Requires [Grolifant 0.8](https://gitlab.com/ysb33rOrg/grolifant/issues/28))
- [x] Settings for specific PDF attributes on the` AsciidoctorJPdfTask`.
- [x]  Using #186 as inspiration allow better support for local themes and downloadable themes
- [x] Check Jacoco configuration to include gradleTest in coverage.
- [x] Fix Gradle 4.9 issue (#254, gradle/gradle#6027).
- [x] Fix Gradle 4.10 issue (#269)
- [x] Fix build to work with JDK11.
- [x] Create a manual test for memory leaks as per #182. The idea is not to run it from CI, but locally.
- [x] RevealJS plugin (https://github.com/asciidoctor/asciidoctor-reveal.js)
- [x] Drop support for AsciidoctorJ 1.5.x (#274)
   - Resolving how the minimum JRuby version is selected in `AsciidoctorJExtension.minimumSafeJRubyVersion`. There must be a better way of doing this. 
   - Remove the need for  `asciidoctorjHasApiJar` in `asciidoctorj-versions.gradle`. 
- [x] Fix annotation warnings in Reveal.js plugin (#281).
- [x] Code coverage reported by coveralls should be 80%+. 
- [x] Depend on `localGroovy()` instead of `groovy-all` in `gradle-plugin-dependencies.gradle` (Depends on https://github.com/gradle/gradle/issues/3698)
- [x] Fix the plugin classpath manifest for tests (#271)

*Items that were fixed*:
- #52 
- #102
- #104 
- #186 
- #193 
- #239
- #242 
- #244 
- #255 
- #256 
- #269 
- #271 
- #273 
- #282 
- #284 
- #285 
- #286 
- #292 
- #298

*See also*:
- ~#237~ 
- asciidoctor/asciidoclet#76
- asciidoctor/asciidoctorj#643
- gradle/gradle#3698
- gradle/gradle#5828
- https://gitlab.com/ysb33rOrg/packer-gradle-plugin/merge_requests/3

**Comment by ysb33r** [comment]
There is big jump in the timings in this test in `AsciidoctorTaskFunctionalSpec` (as seen on Appveyor)

![prent](https://user-images.githubusercontent.com/907624/42123970-54e7f822-7c5b-11e8-93d0-ba7ff059fc79.png)

**Comment by mojavelinux** [comment]
I'm completely in awe of the work you're doing on the 2.0 version. Great job!

While I can't help much with the code, I intend to get involved with the docs part. I still have some work to do to get the docs foundation set up, but once that's in place, it should be easy to incorporate the docs from this project. In the meantime, we can get started by setting up the structure of an Antora component under the docs folder.
