### ISSUE TITLE
Tracking 3.0 development

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-gradle-plugin#357]
This is a tracking issue for all the initial items that needs to be done as part of the final 3.0.0 release:

- [x] AsciidoctorJ 2.0 integration (#342)
  - [x] Update to asciidoctorj 2.0.0 (final release)
  - [x] Update to asciidoctorj-pdf 1.5.0-alpha.17
- [x] Asciidoctor.js integration (#344)
- [x] Remove deprecated features from 2.x
   - [x] Asciidoctor Compatibility Task (#343)
   - [x] Version assignment (in favour of `modules`) (#352)
   - [x] `extensions` (in favour of `docExtensions`) (#352)
- [x] Confirm JDK12 compatibility (#353)
- [x] Split PDF plugins into a separate subproject (#356)
- [x] README needs upgrade section from 2.x to 3.0
   - [x] Mention compatibility task (point to 2.0 README).
- [x] Place module versions in property files. (#363)
- [x] DeckTape support (#376)
- [x] DeckTape testing on GitLab - requires custom Docker image.
- [x] Forward port #390. (#395).
- [x] Multi-language support (#392, #401)
- [x] Add Leanpub plugin (#308)
- [x] Document Leanpub plugin
- [x] Use JRubyGradle 2.0
- [x] Multi-language support (#392, #401, #411)

**For release**:
- [x] Branch `maintenance-2.x` from `master`.
- [x] Merge `development-3.x` to `master`
- [x] Update GH-pages landing page and change `Latest 2.x development update` to `Maintenance 2.x update`.

**Major PRs that are included**:
- #345
- #358 
- #359
- #375
- #395
- #402

**Would be nice, but probably won't get done**:
- Deck2PDF support (#362, #374)
- Remove use of `@stepwise` in Decktape testing (#382).
- Test with two versions of Asciidoctor.js where one is set in the task extension. (#383)
- Add a test project that will run some compatibility tests where as many as possible plugins are combined. (#520)
- Fix DeckTape PNG/JPG export on Windows (#381).
